### ISSUE TITLE
AttributeError: module 'scprep.run' has no attribute 'install_bioconductor'

### ISSUE THREAD

**Issue by jakerhodes** [scottgigante/DEMaP#1]
Hello, Scott,

When trying to run your quick example code from the README file, I get the following error:

AttributeError: module 'scprep.run' has no attribute 'install_bioconductor'

I installed a fresh copy of Python 3.7 (Anaconda), and ran the following before trying to implement your example:

conda install pip
pip install git+https://github.com/scottgigante/DEMaP
conda install rpy2

All of the installations seemed to work.

Any thoughts?

Jake

**Comment by scottgigante** [comment]
Hi @jakerhodes , thanks for bringing this to my attention. You will need to upgrade `scprep` to at least 1.0.0 -- I've added this requirement to the repository so it won't happen again.
