### ISSUE TITLE
Splatter Unavailable for R Version 3.4.4.

### ISSUE THREAD

**Issue by jakerhodes** [scottgigante/DEMaP#3]
Hi Scott,

Sorry to bother you again.  I have tried running your code on Ubuntu 18.04 but ran into more issues.  The most current version of R available on Ubuntu is 3.4.4, but splatter requires an updated version of R.  What software/platform were you using to run the code?  I'm just wondering if I may need to install on older version of splatter.

Jake

**Comment by scottgigante** [comment]
Hi Jake,

I ran the current code with Splatter v1.8.0, which is available in Bioconductor 3.9, R 3.4. I'll add this information to the README.

Scott
